### ISSUE TITLE
Make the old shopCatalogues graphql query available

### ISSUE THREAD

**Issue by zadigus** [shopozor/backend-services#7]
Given a shop id and and category id, Incognito needs to get the corresponding products, as is achieved by [this query](https://github.com/shopozor/graphql/blob/master/calls/shopCatalogue.graphql). For now, we can forget about the `thumbnail` size. 

@donnerc is it possible to enable some kind of pagination in our queries like it was before (relay-like queries)? does there exist anything more relevant to solve pagination issues? assuming Incognito would have to load 1000 products with that query, how would you proceed?

**Comment by donnerc** [comment]
Yes, to achieve pagination, just use the `limit` and `offset` parameters of the query

**Comment by donnerc** [comment]
Here is a query to SHOULD work, but is difficult to test as there is still no data in the DB

```
query ShopCatalogue($shopId: Int!, $categoryId: Int!, $first: Int!, $nbProductsDisplayed: Int!) {
  products(
    limit: $nbProductsDisplayed,
    offset: $first,
    where: {
      _and: {
        category_id: {_eq: $categoryId},
        variants: {
          shop_productvariants: {
            shop_id: {_eq: $shopId}
          }
        }
      }
    }
  ) {
    id
    name
    producer {
      id
      first_name
      last_name
    }
    variants {
      id
      productvariant_state {
        productvariants {
          id
          product_id
        }
        state
      }
      name
      quantity
      quantity_allocated
    }
  }
}
```

**Comment by donnerc** [comment]
We could even optimize the query by setting up a view in postgres that returns all this information without such a complicated graphql query.

**Comment by donnerc** [comment]
Here are the variables to use for the query (example)
```json
{
  "shopId": 1,
  "categoryId": 3,
  "first": 15,
  "nbProductsDisplayed": 10
}
```
